apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: weave-scope
  namespace: default
  annotations: # add the annotation
    helm.fluxcd.io/migrate: "true"
spec:
  helmVersion: v3 # set the helmVersion to v3
  releaseName: weave-scope
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: weave-scope
    version: 1.1.10
  values:
    weave-scope-frontend:
      enabled: true
